### ISSUE TITLE
checkOriginAppId  to false at qlik app publish update

### ISSUE THREAD

**Issue by oadamoVS** [qlik-oss/qlik-cli#22]
in method  qlik app publish update i need to set checkOriginAppId to false. Now is not possible: the default value is true and there is no way to set a false!

**Comment by glooms** [comment]
@oadamoVS There is a way to set it to false but it's a bit hard to find, you can do `--checkOriginAppId=false`, i. e. explicitly setting the value of a boolean. We're trying to see if we can make this more intuitive somehow.

**Comment by oadamoVS** [comment]
> @oadamoVS There is a way to set it to false but it's a bit hard to find, you can do `--checkOriginAppId=false`, i. e. explicitly setting the value of a boolean. We're trying to see if we can make this more intuitive somehow.

Thank you for your replay, It's works fine. Thank you!
