### ISSUE TITLE
Broken link in qlik.dev tutorial

### ISSUE THREAD

**Issue by mountaindude** [qlik-oss/qlik-cli#24]
On [https://qlik.dev/libraries-and-tools/qlik-cli](https://qlik.dev/libraries-and-tools/qlik-cli) there is a link to GitHub, with a broken link:

`Our [releases](https://github.com/qlik-trial/qlik-cli/releases) can be found under releases where you can choose a release suitable for your OS.`

I suspect that `qlik-trial` should be `qlik-oss`....

**Comment by glooms** [comment]
Ah! You're correct. 😅 
Thanks for pointing this out!

**Comment by aihazm** [comment]
this issue has been fixed - thx again @mountaindude
