### ISSUE TITLE
No binaries available for 2.12.0 release

### ISSUE THREAD

**Issue by mountaindude** [qlik-oss/qlik-cli#27]
Only source code for this release, it seems.
Bug/issue in the CI pipeline...?

https://github.com/qlik-oss/qlik-cli/releases/tag/v2.12.0

**Comment by bojanth** [comment]
Hi @mountaindude, thank you for the feedback.
You are right, we had CI issues with that version (there was a delay with the publish of binaries).
This version was fixed later during the day and the following version was released correctly.
