### ISSUE TITLE
Possible to add QSEoW QRS command for security rules?

### ISSUE THREAD

**Issue by mountaindude** [qlik-oss/qlik-cli#28]
There is a whole set of QRS endpoints for security rules at `/systemrule/...`

These are however not exposed in the `qlik qrs` command.
Possible to change this?

It would for example be quite useful to be able to export all security rules to a JSON file for backup purposes.
That can still be done using direct API calls of course - more convenient to have that feature right in qlik cli instead.

**Comment by wennmo** [comment]
Hi @mountaindude, are there more endpoints that you would find useful in your use-case that is not exposed at the moment?

The `qlik qrs` commands exposed today are primarily intended to help in migration scenarios, but I do see the value of adding `systemrule` for backup or versioning purposes.

**Comment by mountaindude** [comment]
Indeed, it's a great little tool to have when setting up more comprehensive backups for client-managed QS.

Having access to security rules would be good.
Same thing for custom properties and tags. 

Just for reference, with data connections I tend to use something like this (simplified..) to get a date-timestamped backup of all data connections. Easy and clean, can be scripted, parametrised etc.

```
qlik qrs dataconnection full | Out-File $backupfolder\data_connections_$((Get-Date).ToString('yyyy-MM-dd')).json
```

There are of course ways of extracting/backing up tags, custom properties, security rules etc using PowerShell scripts, authenticating using certificates. 
Works well but having everything within qlik cli would be a bit cleaner and probably more accessible to users that aren't comfortable writing advanced PowerShell scripts.

**Comment by wennmo** [comment]
Thanks @mountaindude, this is great input. I will bring it up internally and see if we can provide more support for this type of scenario in coming releases.

**Comment by withdave** [comment]
Closing as stale. Please reply here if this request is still of interest.
