### ISSUE TITLE
Default bookmark doesn´t have publish command

### ISSUE THREAD

**Issue by pbergo** [qlik-oss/qlik-cli#3]
Hi,

It was good if we have a <qlik app bookmark publish> command !

I use <qlik app import> command to upload some local qvf files. 
Then to share it with the users, i need to publish the sheets, and i use <qlik app object publish> to do that.
I publish app to a managed space using a <qlik app publish create> and users can view all its contents.

But when the app has a defatult bookmark, there is no option (as I know) to publish the bookmarks. How bookmark is a default, qlik sends a "Access Denied" when accessing the app, even to admin user. 

To avoid this message, i have to access each app and make the default bookmark public.

[]

Pedro

> PS C:\Users\ADITI\Documents\GitHub\qlik-saas-utils> qlik app bookmark layout "2f9de5a1-f425-46e9-b183-8670a0e1bbe0" -a "1a39c50e-7e2c-4825-a28f-cada7825597a"                                                                                   {
  "qInfo": {
    "qId": "2f9de5a1-f425-46e9-b183-8670a0e1bbe0",
    **"qType": "bookmark"**
  },
  "qMeta": {
    "title": "default",
    "description": "",
    "_resourcetype": "app.object",
    "_objecttype": "bookmark",
    "id": "2f9de5a1-f425-46e9-b183-8670a0e1bbe0",
    "approved": false,
    **"published": true,**
    "owner": "auth0|a08D000000QzBmnIAF",
    "ownerId": "M79lApkfHjcWv7aHV1hMICHSBHPTmafp",
    "createdDate": "2020-09-03T20:12:10.764Z",
    "modifiedDate": "2020-09-03T20:29:12.088Z",
    "publishTime": "2020-09-03T20:29:12.088Z",
    "privileges": [
      "read",
      "publish"
    ]
  },

**Comment by csadam** [comment]
I'd also like to have publish command for bookmarks in CLI.
Is there any status estimation of this enhancement?

**Comment by wennmo** [comment]
Hi, `publish` and `unpublish` commands are added for Bookmarks, Dimension and Measures in `v2.20.3` release of `qlik-cli`.

```
# Publish a bookmark
qlik app bookmark publish <bookmark-id> --app <app-id>

# Unpublish a bookmark
qlik app bookmark unpublish <bookmark-id> --app <app-id>

# Publish a dimension
qlik app dimension publish <dimension-id> --app <app-id>

# Unpublish a dimension
qlik app dimension unpublish <dimension-id> --app <app-id>

# Publish a measure
qlik app measure publish <measure-id> --app <app-id>

# Unpublish a measure
qlik app measure unpublish <measure-id> --app <app-id>
```
