### ISSUE TITLE
Object Unpublish not work for $_.objectType -eq "bookmark"

### ISSUE THREAD

**Issue by UnLMTD007** [qlik-oss/qlik-cli#31]
**qlik app object unpublish** for
$object.objectType -eq "story" -OR $object.objectType -eq "sheet"
are works like a charm,
but "bookmark" do not work, please fix
(hugs)

**Comment by wennmo** [comment]
@UnLMTD007 In release `v2.20.3` we have added `publish` and `unpublish` commands for Bookmarks, Dimensions and Measures. So from now on it should be possible for you to use e.g. `qlik app bookmark unpublish <bookmark-id> --app <app-id>`.
