### ISSUE TITLE
Open Source Release

### ISSUE THREAD

**Issue by daviewales** [qlik-oss/qlik-cli#35]
The README states:

> The project will be open-sourced in the near future.

Git blame indicates this was written four years ago.

Are there still plans to open source `qlik-cli`?

My use-case is that I want to understand how the `qlik app unbuild` command works.

**Comment by withdave** [comment]
Closing as stale, but if you still have specific questions feel free to reply here.

**Comment by daviewales** [comment]
I see you removed the promise to open source the CLI in this commit: dece399067b11cad6bf443fedc4fe8735ca0478d, which is disappointing.

When I opened this issue, I was hoping that access to the CLI source code would help me to better understand how to use the REST API to export Qlik apps as JSON. This would allow me to achieve similar functionality within a custom Python script. (We were trying to find a way to backup apps as JSON to git.)

I assume it uses something like the following to get the load script:

- https://qlik.dev/apis/rest/apps/#get-v1-apps-appId-scripts-id

However, it would be nice to see exactly what the CLI uses, and how it converts the rest of the app to JSON.

**Comment by wennmo** [comment]
Hi @daviewales, the `qlik app unbuild` command uses the [JSON-RPC API (QIX)](https://qlik.dev/apis/json-rpc/qix/) for exporting the different assets in an app to JSON. Unfortunately I don't think you can achieve the same using only the REST API today.

It is possible for you to see exactly what is being sent/received over the websocket if you add the `--traffic` flag to the unbuild command.

**Comment by withdave** [comment]
Yep, as @wennmo says, we don't have other ways of extracting via REST components other than the whole binary, and the app script at the moment.

We do have roadmap in this area and I'm hoping we can start to offer app object definitions over REST in 2025, and perhaps a helper function to support unbuilds irrespective of platform.

**Comment by daviewales** [comment]
Thanks. That's helpful.
