### ISSUE TITLE
'app import' is consuming a lot of memory for big apps

### ISSUE THREAD

**Issue by dvasseur** [qlik-oss/qlik-cli#36]
Importing a 1.6GB app to qlikcloud is consuming more than 4GB of memory on the server. Not a bug as such but still, it could be improved I think :)

![app_upload_1](https://github.com/qlik-oss/qlik-cli/assets/6320683/4c61aa3b-5281-44a0-9034-3ec7a0d3d367)

![app_upload_finished](https://github.com/qlik-oss/qlik-cli/assets/6320683/c52e6eae-7471-42ec-8def-019bc39c3bee)

![qlik_version](https://github.com/qlik-oss/qlik-cli/assets/6320683/1ae44cab-07e1-4e08-8550-d8829f7d091b)

**Comment by wennmo** [comment]
Hi @dvasseur, you can use the `--resumable` flag when importing an app which should have a smaller memory footprint since the request will be split into chunks instead.

**Comment by dvasseur** [comment]
Hi @wennmo, much better thanks !
