### ISSUE TITLE
Add option to user basic parsing when invoking rest methods

### ISSUE THREAD

**Issue by d-carrigg** [qlik-oss/qlik-cli#6]
When running Get-QlikApp on a machine where IE Engine is unavailable PowerShell reports the following error: 

```
The response content cannot be parsed because the Internet Explorer engine is not available, or 
Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
```

I dug into the module code and found the culprit on line 66 of `functions/core.ps1`. 
```PowerShell
$result = Invoke-RestMethod @paramInvokeRestMethod @params
```
since no outfile/infile was passed to the `CallRestUri` method it hits the line above instead of the line:

```PowerShell
$result = Invoke-WebRequest @paramInvokeRestMethod @params -UseBasicParsing
```

Can `-UseBasicParsing` be added to the `Invoke-RestMethod` call on like 66 or can a parameter be added to `Get-QlikApp` (and other functions which call `CallRestUri` which enables basic parsing?

I tried using [Default Parameters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parameters_default_values?view=powershell-7.1) like below to no avail:

```PowerShell
$PSDefaultParameterValues["Invoke-RestMethod:UseBasicParsing"] = $True
$PSDefaultParameterValues["Invoke-WebRequest:UseBasicParsing"] = $True

# also tried this with no success
$PSDefaultParameterValues["CallRestUri:extraParams"] = @{UseBasicParsing=$true}
```

I'm running version 1.20.0 of the `Qlik-cli` module

**Comment by sublibra** [comment]
Hello,

This repository hosts releases for Qlik's product agnostic cli tool, [qlik-cli](https://qlik.dev/libraries-and-tools/qlik-cli).

I think this bug was meant for the Windows version https://github.com/ahaydon/Qlik-Cli-Windows, previously named qlik-cli. If so, please open the issue there instead.
